//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_riad_projet_fin_etude.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employé
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employé()
        {
            this.reservation = new HashSet<reservation>();
        }
    
        public string Num_empl { get; set; }
        public string Nom_empl { get; set; }
        public string Prénom_empl { get; set; }
        public string télé_empl { get; set; }
        public string repos { get; set; }
        public string dat_embouchement { get; set; }
        public string Num_gerant { get; set; }
    
        public virtual Gerant Gerant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservation { get; set; }
    }
}
